# Generated by Django 5.0.6 on 2024-06-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0003_alter_contact_user_alter_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='header',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
