# Generated by Django 5.0.6 on 2024-07-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0005_contact_user_education_user_experience_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
